# Thin Julia layer over the generated `libhexaly.jl` ccalls. Mirrors the
# Python `hexaly.optimizer` API surface so the MOI wrapper code reads
# similarly to the upstream Python examples.
#
# Naming convention:
#   * `HexalyOptimizer`, `HxModel`, `HxExpression`, `HxSolution`, `HxParam`,
#     `HxStatistics`, `HxPhase` — managed Julia wrappers.
#   * Modeling helpers are bare functions taking the model as first arg
#     (e.g. `int!(m, lb, ub)`, `sum(m, args...)`). The bang convention is
#     used for the operations that mutate the model (variable creation,
#     constraint posting); pure expression builders have no bang.

# Extend (rather than shadow) Base's reduction operators — the MOI code uses
# bare `sum`, `prod`, `max`, `min` for non-Hexaly arithmetic, and we add
# `HxModel`-first methods below via `_nary`.
import Base: sum, prod, max, min

# `libhexaly` is set by `deps/deps.jl` (generated by `deps/build.jl`) before
# this file is included. See `src/Hexaly.jl`.

# ── Operator / state / status enums ───────────────────────────────────
# Match `include/optimizer/hxoperator.h`, `hxstate.h`, `hxsolutionstatus.h`,
# `hxobjectivedirection.h`.

module HxOp
using Base: Cint
const O_Bool = Cint(0)
const O_Float = Cint(1)
const O_Const = Cint(2)
const O_Sum = Cint(3)
const O_Sub = Cint(4)
const O_Prod = Cint(5)
const O_Max = Cint(6)
const O_Min = Cint(7)
const O_Eq = Cint(8)
const O_Neq = Cint(9)
const O_Geq = Cint(10)
const O_Leq = Cint(11)
const O_Gt = Cint(12)
const O_Lt = Cint(13)
const O_If = Cint(14)
const O_Not = Cint(15)
const O_And = Cint(16)
const O_Or = Cint(17)
const O_Xor = Cint(18)
const O_Abs = Cint(19)
const O_Dist = Cint(20)
const O_Div = Cint(21)
const O_Mod = Cint(22)
const O_Array = Cint(23)
const O_At = Cint(24)
const O_Scalar = Cint(25)
const O_Ceil = Cint(26)
const O_Floor = Cint(27)
const O_Round = Cint(28)
const O_Sqrt = Cint(29)
const O_Log = Cint(30)
const O_Exp = Cint(31)
const O_Pow = Cint(32)
const O_Cos = Cint(33)
const O_Sin = Cint(34)
const O_Tan = Cint(35)
const O_Int = Cint(36)
const O_Piecewise = Cint(37)
const O_List = Cint(38)
const O_Count = Cint(39)
const O_IndexOf = Cint(40)
const O_Partition = Cint(41)
const O_Disjoint = Cint(42)
const O_LambdaFunction = Cint(45)
const O_Argument = Cint(46)
const O_Range = Cint(47)
const O_Contains = Cint(48)
const O_Distinct = Cint(58)
end

const HX_OD_MINIMIZE = Cint(0)
const HX_OD_MAXIMIZE = Cint(1)

const HX_S_MODELING = Cint(0)
const HX_S_RUNNING = Cint(1)
const HX_S_PAUSED = Cint(2)
const HX_S_STOPPED = Cint(3)

const HX_SS_INCONSISTENT = Cint(0)
const HX_SS_INFEASIBLE = Cint(1)
const HX_SS_FEASIBLE = Cint(2)
const HX_SS_OPTIMAL = Cint(3)

# ── Managed Julia handles ──────────────────────────────────────────────

mutable struct HexalyOptimizer
    ptr::hxoptimizer
    function HexalyOptimizer()
        ptr = hx_create_optimizer()
        ptr == C_NULL && error("hx_create_optimizer returned NULL")
        opt = new(ptr)
        finalizer(opt) do o
            if o.ptr != C_NULL
                hx_delete_optimizer(o.ptr)
                o.ptr = C_NULL
            end
        end
        return opt
    end
end

# `HxModel` and `HxParam` are convenience handles that share the optimizer's
# lifetime — the underlying C objects are owned by the optimizer and live
# as long as it does.
struct HxModel
    opt::HexalyOptimizer
end

struct HxParam
    ptr::hxattrs
    opt::HexalyOptimizer  # keep optimizer alive
end

struct HxStatistics
    ptr::hxattrs
    opt::HexalyOptimizer
end

struct HxSolution
    ptr::hxsolution
    opt::HexalyOptimizer
end

# Expression / list / array — these are represented by an integer id within
# the model. We keep a `HexalyOptimizer` reference so we can route operations
# back to the right model.
struct HxExpression
    opt::HexalyOptimizer
    id::Cint
end

# Equality/hashing on expression id so we can use HxExpression as dict keys.
Base.:(==)(a::HxExpression, b::HxExpression) = a.opt === b.opt && a.id == b.id
Base.hash(e::HxExpression, h::UInt) = hash((objectid(e.opt), e.id), h)

# ── Accessors mirroring `optimizer.model`, `optimizer.param`, … ───────

model(opt::HexalyOptimizer) = HxModel(opt)
param(opt::HexalyOptimizer) = HxParam(hx_params(opt.ptr), opt)
statistics(opt::HexalyOptimizer) = HxStatistics(hx_stats(opt.ptr), opt)
solution(opt::HexalyOptimizer) = HxSolution(hx_best_solution(opt.ptr), opt)

state(opt::HexalyOptimizer) = hx_state(opt.ptr)
solve!(opt::HexalyOptimizer) = (hx_solve(opt.ptr); nothing)

# ── Expression builders (modeling-time) ───────────────────────────────

create_constant(m::HxModel, v::Integer) =
    HxExpression(m.opt, hx_create_int_constant(m.opt.ptr, Clonglong(v)))
create_constant(m::HxModel, v::AbstractFloat) =
    HxExpression(m.opt, hx_create_double_constant(m.opt.ptr, Cdouble(v)))
create_constant(m::HxModel, v::Real) =
    v isa Integer ? create_constant(m, Int(v)) : create_constant(m, Float64(v))

# Variable factories: `bool()`, `int(lb, ub)`, `float(lb, ub)`.
function bool!(m::HxModel)
    return HxExpression(m.opt, hx_create_expression(m.opt.ptr, HxOp.O_Bool))
end

function int!(m::HxModel, lb::Integer, ub::Integer)
    lo = create_constant(m, Int(lb))
    hi = create_constant(m, Int(ub))
    id = hx_create_expression_2(m.opt.ptr, HxOp.O_Int, lo.id, hi.id)
    return HxExpression(m.opt, id)
end

function float!(m::HxModel, lb::Real, ub::Real)
    lo = create_constant(m, Float64(lb))
    hi = create_constant(m, Float64(ub))
    id = hx_create_expression_2(m.opt.ptr, HxOp.O_Float, lo.id, hi.id)
    return HxExpression(m.opt, id)
end

# n-ary expression with HxExpression operands.
function _nary(m::HxModel, op::Cint, exprs)
    id = hx_create_expression(m.opt.ptr, op)
    for e in exprs
        _add_operand!(m, id, e)
    end
    return HxExpression(m.opt, id)
end

_add_operand!(m::HxModel, expr_id::Cint, operand::HxExpression) =
    hx_expr_add_operand(m.opt.ptr, expr_id, operand.id)
_add_operand!(m::HxModel, expr_id::Cint, c::Integer) =
    _add_operand!(m, expr_id, create_constant(m, Int(c)))
_add_operand!(m::HxModel, expr_id::Cint, c::AbstractFloat) =
    _add_operand!(m, expr_id, create_constant(m, Float64(c)))

# Lift "any" argument (constant or expression) into an HxExpression.
_lift(m::HxModel, e::HxExpression) = e
_lift(m::HxModel, c::Real) = create_constant(m, c)

# Common operators (variadic where it makes sense)
for (name, op) in (
    (:sum, :(HxOp.O_Sum)), (:prod, :(HxOp.O_Prod)),
    (:max, :(HxOp.O_Max)), (:min, :(HxOp.O_Min)),
    (:and_, :(HxOp.O_And)), (:or_, :(HxOp.O_Or)),
)
    @eval $(name)(m::HxModel, args...) =
        _nary(m, $op, (_lift(m, a) for a in args))
end

# Binary operators
for (name, op) in (
    (:eq, :(HxOp.O_Eq)), (:neq, :(HxOp.O_Neq)),
    (:leq, :(HxOp.O_Leq)), (:geq, :(HxOp.O_Geq)),
    (:lt, :(HxOp.O_Lt)), (:gt, :(HxOp.O_Gt)),
    (:sub, :(HxOp.O_Sub)), (:div_, :(HxOp.O_Div)),
    (:mod_, :(HxOp.O_Mod)), (:pow_, :(HxOp.O_Pow)),
    (:dist, :(HxOp.O_Dist)),
)
    @eval function $(name)(m::HxModel, a, b)
        ea, eb = _lift(m, a), _lift(m, b)
        id = hx_create_expression_2(m.opt.ptr, $op, ea.id, eb.id)
        return HxExpression(m.opt, id)
    end
end

# Unary operators
for (name, op) in (
    (:not_, :(HxOp.O_Not)), (:abs_, :(HxOp.O_Abs)),
    (:ceil_, :(HxOp.O_Ceil)), (:floor_, :(HxOp.O_Floor)),
    (:round_, :(HxOp.O_Round)),
)
    @eval function $(name)(m::HxModel, a)
        e = _lift(m, a)
        id = hx_create_expression_1(m.opt.ptr, $op, e.id)
        return HxExpression(m.opt, id)
    end
end

# count(seq) — arity 1 (no second arg) or count(seq, x) for the
# "count occurrences" form.
count_(m::HxModel, seq::HxExpression) =
    HxExpression(m.opt, hx_create_expression_1(m.opt.ptr, HxOp.O_Count, seq.id))

# iif(cond, then, else_)
function iif(m::HxModel, c, t, e)
    ec, et, ee = _lift(m, c), _lift(m, t), _lift(m, e)
    id = hx_create_expression_3(m.opt.ptr, HxOp.O_If, ec.id, et.id, ee.id)
    return HxExpression(m.opt, id)
end

# at(arr, indices...) — indexed access. Hexaly's O_At expression takes the
# array as the first operand and the indices as subsequent operands.
at(m::HxModel, arr::HxExpression, idxs...) = _nary(m, HxOp.O_At, (arr, idxs...))

# `contains(seq, x)` — element-of (used for lists).
contains_(m::HxModel, seq, x) =
    HxExpression(m.opt, hx_create_expression_2(m.opt.ptr,
        HxOp.O_Contains, _lift(m, seq).id, _lift(m, x).id))

# `index_of(seq, x)` — position of x in seq.
index_of(m::HxModel, seq, x) =
    HxExpression(m.opt, hx_create_expression_2(m.opt.ptr,
        HxOp.O_IndexOf, _lift(m, seq).id, _lift(m, x).id))

# list(n) — list decision variable over 0..n-1.
function list!(m::HxModel, n::Integer)
    n_const = create_constant(m, Int(n))
    id = hx_create_expression_1(m.opt.ptr, HxOp.O_List, n_const.id)
    return HxExpression(m.opt, id)
end

# range(lb, ub) — integer range (exclusive upper bound, like Python).
function range_(m::HxModel, lb, ub)
    elb, eub = _lift(m, lb), _lift(m, ub)
    id = hx_create_expression_2(m.opt.ptr, HxOp.O_Range, elb.id, eub.id)
    return HxExpression(m.opt, id)
end

# partition(lists...) — constraint that the lists form a partition.
partition(m::HxModel, lists::AbstractVector{HxExpression}) =
    _nary(m, HxOp.O_Partition, lists)
partition(m::HxModel, lists::HxExpression...) = _nary(m, HxOp.O_Partition, lists)

# distinct(seq) — built-in distinctness on a list.
distinct(m::HxModel, seq::HxExpression) =
    HxExpression(m.opt, hx_create_expression_1(m.opt.ptr, HxOp.O_Distinct, seq.id))

# array(elements...) or array(range, lambda, init)
function array(m::HxModel, elements::AbstractVector)
    exprs = [_lift(m, e) for e in elements]
    return _nary(m, HxOp.O_Array, exprs)
end
array(m::HxModel, args...) = _nary(m, HxOp.O_Array, args)

# lambda_function(f) where `f(args...) -> expression`.
#
# Hexaly's `O_LambdaFunction` is *modeling-time*: we create one `O_Argument`
# expression per parameter, call the user's Julia function with those
# placeholder expressions, and use the returned expression as the lambda
# body. `nargs` is the arity (1 or 2 are the only cases we use in MOI code).
function lambda_function(m::HxModel, f::Function; nargs::Int = 1)
    arg_exprs = HxExpression[
        HxExpression(m.opt, hx_create_expression(m.opt.ptr, HxOp.O_Argument))
        for _ in 1:nargs
    ]
    body = f(arg_exprs...)
    body isa HxExpression || error(
        "lambda_function: closure must return HxExpression; got $(typeof(body))",
    )
    # Hexaly expects `arguments..., body` as the operand order (matching
    # the Python `create_lambda_function`).
    lam_id = hx_create_expression(m.opt.ptr, HxOp.O_LambdaFunction)
    for a in arg_exprs
        hx_expr_add_operand(m.opt.ptr, lam_id, a.id)
    end
    hx_expr_add_operand(m.opt.ptr, lam_id, body.id)
    return HxExpression(m.opt, lam_id)
end

# ── Modeling-time mutations ───────────────────────────────────────────

function add_constraint!(m::HxModel, e::HxExpression)
    hx_add_constraint(m.opt.ptr, e.id)
    return e
end

function add_objective!(m::HxModel, e::HxExpression, direction::Cint = HX_OD_MINIMIZE)
    hx_add_objective(m.opt.ptr, e.id, direction)
    return e
end

minimize!(m::HxModel, e::HxExpression) = add_objective!(m, e, HX_OD_MINIMIZE)
maximize!(m::HxModel, e::HxExpression) = add_objective!(m, e, HX_OD_MAXIMIZE)

close!(m::HxModel) = (hx_close(m.opt.ptr); nothing)
is_closed(m::HxModel) = hx_is_closed(m.opt.ptr)

nb_objectives(m::HxModel) = Int(hx_nb_objectives(m.opt.ptr))
get_objective(m::HxModel, i::Integer) =
    HxExpression(m.opt, hx_objective(m.opt.ptr, Cint(i)))

# Expression name (optional, used for variable naming).
function set_name!(e::HxExpression, name::AbstractString)
    hx_expr_set_name(e.opt.ptr, e.id, name)
    return e
end

function get_name(e::HxExpression)
    buf = Vector{UInt8}(undef, 256)
    n = hx_expr_name(e.opt.ptr, e.id, buf, Cint(length(buf)))
    return unsafe_string(pointer(buf), max(0, Int(n)))
end

# ── Solution accessors ────────────────────────────────────────────────

# Hexaly returns expression *values* via the solution handle, indexed by
# the expression id. For decision variables, the value type follows the
# variable's domain (int / float). Boolean variables come back as 0/1 ints.

int_value(s::HxSolution, e::HxExpression) =
    Int(hx_solution_int_value(s.ptr, e.id))
double_value(s::HxSolution, e::HxExpression) =
    Float64(hx_solution_double_value(s.ptr, e.id))

# Convenience for the common pattern `e.value` on the optimizer.
# When `is_integer` is not passed, the value type is auto-detected via
# `hx_expr_type` (HXVT_INT vs HXVT_DOUBLE). The explicit keyword override
# is kept for sites that already know the type.
const HXVT_INT = 2

function value(e::HxExpression; is_integer::Union{Bool,Nothing} = nothing)
    sol = hx_best_solution(e.opt.ptr)
    if is_integer === nothing
        is_integer = (hx_expr_type(e.opt.ptr, e.id) == HXVT_INT)
    end
    return is_integer ? Int(hx_solution_int_value(sol, e.id)) :
                        Float64(hx_solution_double_value(sol, e.id))
end

solution_status(s::HxSolution) = hx_solution_status(s.ptr)

# Collection-valued expressions (lists). Returns a Vector{Int} with the
# elements of the solved list, in order.
function collection_value(s::HxSolution, e::HxExpression)
    coll = hx_solution_collection_value(s.ptr, e.id)
    n = Int(hx_collection_count(coll))
    return Int[hx_collection_get(coll, Cint(i)) for i = 0:(n-1)]
end
collection_value(e::HxExpression) = collection_value(solution(e.opt), e)

# ── Parameters (HxParam) ──────────────────────────────────────────────
#
# Hexaly parameters use a typed attribute API:
#   `hx_attrs_get_int / set_int / get_double / set_double / ...`
# We expose a small typed helper plus a string-keyed fallback that
# auto-detects the type via `hx_attrs_type`.

function set_param!(p::HxParam, name::AbstractString, value::Integer)
    hx_attrs_set_int(p.ptr, name, Cint(value))
    return p
end
function set_param!(p::HxParam, name::AbstractString, value::AbstractFloat)
    hx_attrs_set_double(p.ptr, name, Cdouble(value))
    return p
end
function set_param!(p::HxParam, name::AbstractString, value::AbstractString)
    hx_attrs_set_string(p.ptr, name, value)
    return p
end
function set_param!(p::HxParam, name::AbstractString, value::Bool)
    hx_attrs_set_bool(p.ptr, name, value)
    return p
end

# Set `time_limit` / `verbosity` via a typed helper.
# The Hexaly attribute names are camelCase (e.g. `timeLimit`, `nbThreads`),
# not snake_case — the Python wrapper does its own name mangling.
time_limit!(p::HxParam, seconds::Integer) = set_param!(p, "timeLimit", Int(seconds))
verbosity!(p::HxParam, level::Integer) = set_param!(p, "verbosity", Int(level))
nb_threads!(p::HxParam, n::Integer) = set_param!(p, "nbThreads", Int(n))
seed!(p::HxParam, s::Integer) = set_param!(p, "seed", Int(s))

function get_param_int(p::HxParam, name::AbstractString)
    return Int(hx_attrs_get_int(p.ptr, name))
end
function get_param_double(p::HxParam, name::AbstractString)
    return Float64(hx_attrs_get_double(p.ptr, name))
end

# Statistics
running_time(s::HxStatistics) = Float64(hx_attrs_get_int(s.ptr, "runningTime"))

# ── Operator overloading sugar (mirrors Python ``a + b`` etc.) ─────────
# Hexaly's Python wrapper overloads arithmetic and comparison so model
# expressions read naturally. We do the same on `HxExpression` so the MOI
# code can keep using `+`, `<=`, `==`, etc.

# Helpers: looking up the model.
_m(e::HxExpression) = HxModel(e.opt)

Base.:+(a::HxExpression, b::HxExpression) = sum(_m(a), a, b)
Base.:+(a::HxExpression, b::Real) = sum(_m(a), a, b)
Base.:+(a::Real, b::HxExpression) = sum(_m(b), a, b)

Base.:-(a::HxExpression, b::HxExpression) = sub(_m(a), a, b)
Base.:-(a::HxExpression, b::Real) = sub(_m(a), a, b)
Base.:-(a::Real, b::HxExpression) = sub(_m(b), a, b)

Base.:*(a::HxExpression, b::HxExpression) = prod(_m(a), a, b)
Base.:*(a::HxExpression, b::Real) = prod(_m(a), a, b)
Base.:*(a::Real, b::HxExpression) = prod(_m(b), a, b)

Base.:(==)(a::HxExpression, b::Real) = eq(_m(a), a, b)
Base.:(==)(a::Real, b::HxExpression) = eq(_m(b), a, b)
# Note: HxExpression-HxExpression `==` is hash-equality (defined above).
# Use `eq(m, a, b)` explicitly for the modeling-time equality expression.

Base.:<=(a::HxExpression, b::HxExpression) = leq(_m(a), a, b)
Base.:<=(a::HxExpression, b::Real) = leq(_m(a), a, b)
Base.:<=(a::Real, b::HxExpression) = leq(_m(b), a, b)

Base.:>=(a::HxExpression, b::HxExpression) = geq(_m(a), a, b)
Base.:>=(a::HxExpression, b::Real) = geq(_m(a), a, b)
Base.:>=(a::Real, b::HxExpression) = geq(_m(b), a, b)

Base.:<(a::HxExpression, b::HxExpression) = lt(_m(a), a, b)
Base.:<(a::HxExpression, b::Real) = lt(_m(a), a, b)
Base.:<(a::Real, b::HxExpression) = lt(_m(b), a, b)

Base.:>(a::HxExpression, b::HxExpression) = gt(_m(a), a, b)
Base.:>(a::HxExpression, b::Real) = gt(_m(a), a, b)
Base.:>(a::Real, b::HxExpression) = gt(_m(b), a, b)

# Indexed access: `seq[i]` -> `at(model, seq, i)`.
Base.getindex(e::HxExpression, idx::Union{Integer,HxExpression}) =
    at(_m(e), e, idx)
Base.getindex(e::HxExpression, idxs...) = at(_m(e), e, idxs...)
